# Daily update for the data and output

name: Update Data and Output

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Nodejs
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install nodejs
        sudo apt install npm
        sudo nodejs -v
    - name: Install Orca
      run: |
        sudo npm install -g electron@6.1.4 orca --unsafe-perm=true --allow-root
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the Update
      run: |
        python update.py
    - name: Commit the Changes
      run: |
        git config --global user.email "stephen.d.gibson@gmail.com"
        git config --global user.name "Stephen D. Gibson"
        git add .
        git commit -m "automatic update"
        git pull
        git push



