# Daily update for the data and output

name: Update Data and Output

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Orca
      run: |
        echo $PATH
        docker pull quay.io/plotly/orca
        docker run -i quay.io/plotly/orca graph --help
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the Update
      run: |
        python update.py
    - name: Commit the Changes
      run: |
        git config --global user.email "stephen.d.gibson@gmail.com"
        git config --global user.name "Stephen D. Gibson"
        git add .
        git commit -m "automatic update"
        git push



