# Daily update for the data and output

name: Update Data and Output

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        conda install -c plotly plotly-orca
    - name: Run the Update
      run: |
        conda install -c plotly plotly-orca
        python update.py
    - name: Commit the Changes
      run: |
        git add .
        git commit -m "automatic update"
        git push
        


